#!/usr/bin/env python2.7

import subprocess, sys, os, re

def switch():
    '''Cycle through all sound cards.'''

    # Get current card
    dotasoundrc = os.path.expanduser('~/.asoundrc')
    curcard = None
    if os.path.isfile(dotasoundrc):
      m = re.match(r'pcm\.!default sysdefault:(\w+)', file(dotasoundrc).read())
      if m:
        curcard = m.group(1)

    cards = []
    for line in subprocess.check_output(['aplay', '-l']).splitlines():
      m = re.match(r'card \d+: (\w+)', line)
      if m:
        cards.append(m.group(1))

    if curcard in cards:
      curidx = cards.index(curcard)
    else:
      curidx = -1

    curidx = (curidx + 1) % len(cards)

    card = cards[curidx]
    print 'Using card "%s"' % card
    conf = 'pcm.!default sysdefault:%s' % card

    file(dotasoundrc, 'w').write(conf)

if __name__ == '__main__':
    switch()
