#!/bin/bash

DEV=/dev/sda
MNT=/media/backup
BUP_DIR="$MNT/bup/"
HOST="$(hostname)"
PATHS=$HOME/.backup-paths
EXCLUDE=$HOME/.backup-exclude

# Bake BUP_DIR into `bup` command
BUP_BIN="$(which bup)"
if [ -z "$BUP_BIN" ] ; then
    echo "Bup is not installed"
    exit 1
fi
function bup () {
    sudo "$BUP_BIN" -d "$BUP_DIR" $@
}

# Mount?
if [ $# = 1 ] && [ $1 = "mount" ] ; then
    if mount | grep -q "$MNT" ; then
        echo "$MNT is already mounted"
        exit
    fi
    mount.luks $DEV $MNT
    exit
fi

# Assert that the disk is mounted
if ! mount | grep -q "$MNT" ; then
    echo "$MNT is not mounted"
    exit 1
fi

# Maybe initialize
if ! bup ls >/dev/null ; then
    bup init
fi

# Extra commands
case $1 in
    now)
        if [ -f $EXCLUDE ] ; then
            EXCL="--exclude-rx-from=$EXCLUDE"
        else
            EXCL=""
        fi

        while read line ; do
            # Strip comments
            line="${line%%#*}"
            # Empty lines
            [ -z "$line" ] && continue
            echo -e "\033[32;1m+\033[m" "$line"
            bup index --print --modified --status --update --one-file-system \
                "$EXCL" "$line"
        done < "$PATHS"
        bup save --name="$HOST" "/"
        ;;

    umount)
        umount.luks $MNT
        ;;

    *)
        # Otherwise just act as a front-end for Bup
        bup $@
        ;;
esac
