#!/bin/bash
set -e

__usage() {
    1>&2 echo "usage: $0 [-c|--encrypt] /path/to/dir_or_file [DEVICE]"
    exit 1
}

if [ "$1" = "-c" -o "$1" = "--encrypt" ] ; then
    ENCRYPT=yes
    shift
fi

if [ $# -lt 1 ] ; then
    __usage
fi

SRC="$(realpath "$1")"
if [ ! -e "$SRC" ] ; then
    1>&2 echo "$SRC does not exist"
    exit 1
fi

if [ $# -gt 1 ] ; then
    DEV="$2"
else
    DEV=/dev/sr0
fi

TMP=$(mktemp /tmp/burn-XXXXXX)
ISO="$TMP".iso
TAR="$TMP".tar
GPG="$TAR".gpg
LBL="$(date +%F_%T)"
trap "shred -u \"$ISO\" \"$TAR\" \"$GPG\"" EXIT

set -x
if [ -n "$ENCRYPT" ] ; then
    tar -cf "$TAR" "$SRC"
    gpg -c "$TAR"
    SRC="$GPG"
fi

xorriso -as mkisofs -v -J -r -V "$LBL" -o "$ISO" "$SRC"
xorriso -as cdrecord -v dev="$DEV" -dao "$ISO"
