#!/bin/sh

if [ $# -lt 1 -o $# -gt 2 ] ; then
    echo "usage: $0 [<section>] <page>"
    exit 1
fi

if [ $# -eq 2 ] ; then
    case $1 in
        [1-9])
            SECTION=$1
            shift
            ;;
        *)
            echo "<section> must be a number between 1 and 9"
            exit 1
            ;;
    esac
fi

PAGE=$1
shift

man -t $SECTION $PAGE | ps2pdf - > $PAGE.pdf
